### ISSUE TITLE
求修复..

### ISSUE THREAD

**Issue by lsz7575** [caoli5288/permission#1]
permission-1.4  - simpleorm-0.3.1.jar
ubunt 16.4 .
mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper

设置offline: true  数值显示正常..
设置offline: false 添加临时权限就报错了..

使用     /permission 玩家              查看
value=null,null,null,null,nullnullnull,null,nullnull,nullnull,nullnullnull,nullnullnullnullnullnullnullnullnullnul
outdated值正常
value=null,null,null,null,null,null,null,null
outdated值正常
mysql里面有建表,里面数据都是正常的..再次添加权限天数报错..

启动的时候有个ERROR
[15:30:02 INFO]: [Permission] Enabling Permission v1.4
[15:30:02 ERROR]: ebean.properties not found

spigot-1.8.8-R0.1-SNAPSHOT-latest.报错
[14:46:56 WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[14:46:56 WARN]: org.apache.commons.lang.UnhandledException: Plugin Permission v1.4 generated an exception while executing task 56
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update permission_user set outdated=? where id=? and name=? and value=? and type=? and outdated=? and created=?] bind[null]
    at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:122)
    at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:107)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85)
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:504)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:436)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282)
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629)
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619)
    at com.mengcraft.simpleorm.EbeanHandler.save(EbeanHandler.java:178)
    at com.mengcraft.permission.Commander.lambda$execute$8(Commander.java:220)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

craftbukkit-1.8.8-R0.1-SNAPSHOT-latest 报错..

[14:58:31 WARN]: Exception in thread "pool-3-thread-5" 
[14:58:31 WARN]: org.apache.commons.lang.UnhandledException: Plugin Permission v1.4 generated an exception while executing task 29
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update permission_user set outdated=? where id=? and name=? and value=? and type=? and outdated=? and created=?] bind[null]
    at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:122)
    at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:107)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85)
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:504)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:436)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282)
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629)
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619)
    at com.mengcraft.simpleorm.EbeanHandler.save(EbeanHandler.java:178)
    at com.mengcraft.permission.Commander.lambda$execute$8(Commander.java:220)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by caoli5288** [comment]
offline: true 的时候是不使用数据库的哦
可能明天才有时间看

**Comment by lsz7575** [comment]
@caoli5288 我知道..false 是使用mysql...true是本地建一个sqlit...默认是true本地建立一个..
DeluxeJoin 和你这个 permission 不兼容吗?
DeluxeJoin 用 PermissionsEx  能正常使用.所以我配置的是没有问题的..

**Comment by caoli5288** [comment]
PermissionsEx 是玩家进服前获取权限，这插件是玩家进服后，进服瞬间就需要的权限这插件是不支持的

**Comment by lsz7575** [comment]
@caoli5288  进服后支持也挺好的...我试了试windows平台用spiot1.8启动的时候也有段这个插件的报错...
不管是true还是false,
[16:45:47 ERROR]: ebean.properties not found
这个不用理会吗?还是说这个是导致使用mysql不正常的原因..

**Comment by caoli5288** [comment]
那个没影响的才对，总之我明天才能腾出手看看- -!

**Comment by caoli5288** [comment]
![2016-07-06 18-36-55](https://cloud.githubusercontent.com/assets/3120587/16615355/b7bb9de2-433b-11e6-86d2-e670b2b1857e.png)
话说我初步测试是没问题的。。。spigot-1.8.8,simpleorm-0.3.1,permission-1.4

**Comment by lsz7575** [comment]
@caoli5288 你没用mysql吗?..本地那个我也正常..

**Comment by caoli5288** [comment]
就是用的mysql

**Comment by lsz7575** [comment]
@caoli5288 我懂了..mysql..建表要建立gbk2312..浪费你宝贵的时间,非常抱歉...谢谢..
