### ISSUE TITLE
中文玩家名报错

### ISSUE THREAD

**Issue by l89669** [caoli5288/permission#5]
Stack trace: 

00:36:14] [Craft Scheduler Thread - 34/WARN] [/]: Exception in thread "Craft Scheduler Thread - 34" 
[00:36:15] [Craft Scheduler Thread - 34/WARN] [/]: org.apache.commons.lang.UnhandledException: Plugin Permission v1.4 generated an exception while executing task 97
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=' 
Bind values:[一二三四五六, 2017-04-20 00:36:14.496] 
Query was:
select t0.id c0, t0.name c1, t0.value c2, t0.type c3, t0.outdated c4, t0.created c5 
from permission_user t0 
where t0.name = ?  and t0.outdated > ?  
order by t0.type desc 

	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:849)
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:829)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:238)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:104)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:344)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1469)
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:906)
	at com.mengcraft.permission.manager.Fetcher.lambda$fetch$11(Fetcher.java:162)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.sql.SQLException: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeQuery(ExtendedPreparedStatement.java:150)
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:416)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:198)
	... 10 more

**Comment by caoli5288** [comment]
看提示是数据库字符集设定的问题，请调整你的数据库设置。

**Comment by l89669** [comment]
已解决，但是是否有对用户更友好的方法来解决呢？比如在代码中加入自动识别数据库字符集，并自动转换的功能，或者在创建表时强制创建UTF8的表

**Comment by caoli5288** [comment]
数据库编码当然是在数据库里面统一解决好，而不是建表的时候各弄各的。

**Comment by l89669** [comment]
我是在把服务器升级支持中文ID的时候出现的这个问题，但是authme并没有报这样的错误，想来它肯定有它自己的兼容代码:-)
